### ISSUE TITLE
[prelaunch] required

### ISSUE THREAD

**Issue by ljosberinn** [ljosberinn/keystone-heroes#67]
- [x] discord invite link to footer & `.github/ISSUE_TEMPLATE/feature_request.yml`
- [x] responsiveness of pulls (#60)
- [x] add remaining missing POIs (#65)
- [x] improve fight selection
- [x] finish Buy Me A Coffee & Patreon setup
- [x] purge prod db (optional)
- [x] add `Throw Cleaver` from NW to tracked events
- [x] last mobile issues of pulls
- ~~[ ] remove `Week` and everything connected to it. add timestamp of log time to Report or something so we can still sort by date~~
- [x] fix opengraph image (needs absolute url) (#74 is related)
- [x] fix sentry server side or remove it (https://github.com/getsentry/sentry-javascript/blob/master/packages/nextjs/README.md)
- [x] add legend infos
